version: "3.3"

services:
  pureride-api:
    container_name: pureride-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:5007
    volumes:
      - ./:/usr/src/pureride
    working_dir: /usr/src/pureride

    networks:
      - monorepo-network

    # PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  pureride-batch:
    container_name: pureride-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:5008
    volumes:
      - ./:/usr/src/pureride
    working_dir: /usr/src/pureride

    networks:
      - monorepo-network

    # PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
